Azure-Samples/communication-services-ios-quickstarts

.gitignore
Add Voice Calling/.gitignore
Add Voice Calling/AzureCommunicationCallingSample.xcodeproj/project.pbxproj
Add Voice Calling/AzureCommunicationCallingSample.xcworkspace/contents.xcworkspacedata
Add Voice Calling/AzureCommunicationCallingSample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Add Voice Calling/PodFile
Add Voice Calling/Podfile.lock
Add Voice Calling/README.md

* ...
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
Get the voice video calling sample from here
https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/Add%20Voice%20Calling
```
Create Podfile as in quick start sample and follow the instructions there
```
```
Make sure the xcoworkspace is created properly
* ...

Add cocoapods support instruction

---

join-call-to-teams-meeting/Podfile
join-call-to-teams-meeting/README.md
join-call-to-teams-meeting/join-call-to-teams-meeting.xcodeproj/project.pbxproj
join-call-to-teams-meeting/join-call-to-teams-meeting.xcodeproj/project.xcworkspace/contents.xcworkspacedata
join-call-to-teams-meeting/join-call-to-teams-meeting.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
join-call-to-teams-meeting/join-call-to-teams-meeting/Assets.xcassets/AccentColor.colorset/Contents.json
join-call-to-teams-meeting/join-call-to-teams-meeting/Assets.xcassets/AppIcon.appiconset/Contents.json
join-call-to-teams-meeting/join-call-to-teams-meeting/Assets.xcassets/Contents.json
join-call-to-teams-meeting/join-call-to-teams-meeting/ContentView.swift
join-call-to-teams-meeting/join-call-to-teams-meeting/Info.plist
join-call-to-teams-meeting/join-call-to-teams-meeting/Podfile
join-call-to-teams-meeting/join-call-to-teams-meeting/Preview Content/Preview Assets.xcassets/Contents.json
join-call-to-teams-meeting/join-call-to-teams-meeting/join_call_to_teams_meetingApp.swift

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Joins ACS to teams meeting quick start sample

---

Add Video Calling/iOSVideo/ContentView.swift
Add Video Calling/iOSVideo/IncomingCallHandler.swift

Remove usage of unnecessary variable `oldCallKitEnabledState`
Minor refactor
Add comments when call is accepted via CallKit
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```

Remove unnecessary change and minor refactor

---

ui-library-quick-start/Podfile
ui-library-quick-start/Podfile.lock
ui-library-quick-start/UILibraryQuickStart/ViewController.swift

* Increase UILibraryQuickStart AzureCommunicationUI pod to 1.0.0-beta.2 version
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
* the app works as expected

Update AzureCommunicationUI pod version

---

ui-library-quick-start/Podfile
ui-library-quick-start/UILibraryQuickStart/ViewController.swift

* Update communication ui pod version
Note: Please do NOT merge this PR before releasing the pod
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe: Update communication ui pod version
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update Podfile and code for beta2

---

ui-library-quick-start/Podfile

Updating documentation to ga version 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

[Documentation] Update the pod version to GA

---

add-chat/ChatQuickstart/ViewController.swift

* ChatQuickstart: Fix add participant error message logic
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
*  Run Chat Quickstart and inspect printed message from add participant step
* "Added participant" should be printed for valid Azure Communication Services Identity
* "Error adding participant" should be printed for invalid Azure Communication Services Identity

ChatQuickstart: Fix add participant error message logic

---

ui-chat/Podfile.lock

* Fix pod lock file for UI-Chat Quick Start
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix pod lock file for UI-Chat Quick Start

---

ui-chat/Podfile
ui-chat/Podfile.lock

* lockfile to be updated when new version is released *
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other: Release
```
```
run pod install --repo-update
```
* ...

[Release] Updated Podfile to AzureCommunicationUIChat_1.0.0-beta.2

---

add-chat-push-notifications/.gitignore
add-chat-push-notifications/Podfile
add-chat-push-notifications/Podfile.lock
add-chat/.gitignore
add-chat/ChatQuickstart/ViewController.swift
add-chat/Podfile
add-chat/Podfile.lock

* Updated samples
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

[Documentation] Chat quickstarts update

---

ui-chat/Podfile
ui-chat/Podfile.lock

* ui chat sample update
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
``

[Documentation] AzureCommunicationUIChat version update

---

Add Video Calling/Podfile
Add Video Calling/Podfile.lock
Add Video Calling/iOSVideo/CallKitHelper.swift
Add Video Calling/iOSVideo/ContentView.swift
Add Video Calling/iOSVideo/IncomingCallHandler.swift

* Fix bugs in the app when an incoming call is accepted.
* Use the new API's in `2.3.0-beta.5` version of Calling SDK.
* Add Hold/Resume and Mute/Unmute options.
* Minor code refactor.
```
[x] Yes
[ ] No
```
```
[x] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...

Changes for 2.3.0-beta.5

---

add-video-calling/iOSVideo/CallKitHelper.swift
add-video-calling/iOSVideo/ContentView.swift
add-video-calling/iOSVideo/IncomingCallHandler.swift

* Fix bug when switching microphone.
* No need to report incoming call to CallKit from app when using CallKit in SDK.
* Fix compilation issue.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix minor bugs and upgrade to 2.4.1 of ACS Calling SDK.

---

join-room-call/.gitignore
join-room-call/Podfile
join-room-call/Podfile.lock
join-room-call/README.md
join-room-call/roomsquickstart.xcodeproj/project.pbxproj
join-room-call/roomsquickstart.xcodeproj/project.xcworkspace/contents.xcworkspacedata
join-room-call/roomsquickstart.xcworkspace/contents.xcworkspacedata
join-room-call/roomsquickstart/Assets.xcassets/AccentColor.colorset/Contents.json
join-room-call/roomsquickstart/Assets.xcassets/AppIcon.appiconset/Contents.json
join-room-call/roomsquickstart/Assets.xcassets/Contents.json
join-room-call/roomsquickstart/CallHandler.swift
join-room-call/roomsquickstart/Info.plist
join-room-call/roomsquickstart/Preview Content/Preview Assets.xcassets/Contents.json
join-room-call/roomsquickstart/Views/HomePageView.swift
join-room-call/roomsquickstart/Views/ParticipantView.swift
join-room-call/roomsquickstart/roomsquickstartApp.swift

Introduce iOS Sample for Rooms
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

[Rooms][Sample App] Introduce iOS Rooms Sample

---

ui-calling/Podfile
ui-calling/Podfile.lock

* Update Calling UI to use 1.4.0 SDK
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update Calling UI to use 1.4.0 SDK

---

add-chat-push-notifications/Podfile
add-chat-push-notifications/Podfile.lock
add-chat/Podfile
add-chat/Podfile.lock

* Update Chat samples to use 1.3.3 SDK
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: version update
```

[Chat] Update Chat samples to use 1.3.3 SDK

---

ui-chat/Podfile
ui-chat/Podfile.lock

* Update AzureCommunicationUIChat to 1.0.0-beta.4
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

[ChatUI] Update AzureCommunicationUIChat to 1.0.0-beta.4

---

add-video-calling/iOSVideo/CallHandler.swift
add-video-calling/iOSVideo/ContentView.swift
add-video-calling/iOSVideo/IncomingCallHandler.swift
add-video-calling/iOSVideo/iOSVideoApp.swift

Adjust CTE (Custom Teams Endpoint) support example in ACS SDK to the updated new APIs
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...

[CTE] Adjust CTE (Custom Teams Endpoint) example to updated APIs

---

add-chat-push-notifications/SwiftPushTestNotificationExtension/NotificationService.swift

This PR introduces the updates to enhance the user experience of the notification system in our Chat SDK. Specifically, we've made two changes:
1.Centralized Content Handler Call: We've moved the contentHandler call to ensure it's executed in all execution paths, addressing an issue where customized notifications could fail to deliver. Also it can reduce the delay time of notification delivery.
2.Fallback Notification Content: Introduced default notification content ("New Message" and "Please tap here to see the message.") to ensure a fallback message is always available, improving the user experience in error scenarios or unexpected data formats.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, …
```

FixSampleAppToImproveNotificationDelivery

---

add-chat-push-notifications-auto-renew/Podfile
add-chat-push-notifications/Podfile
add-chat/Podfile

* Update the package version in pod files
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Azure communication chat 1.3.6 Release

---

add-chat-push-notifications-auto-renew/Podfile
add-chat-push-notifications-auto-renew/Podfile.lock
add-chat-push-notifications/Podfile
add-chat-push-notifications/Podfile.lock
add-chat/Podfile
add-chat/Podfile.lock
join-chat-to-teams-meeting/Podfile.lock
ui-chat/Podfile
ui-chat/Podfile.lock

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update dependencies for chat and chat ui library
